# Everything can be omitted, including the absence of this file.

# Path of the folder containing `index.html`
# If absent, it will assume `.`
www: "./www"

# If 0 or absent, it will be randomly assigned.
port: 24000

# If non-empty string value, it can used in request headers
# e.g. Authorization: `Bearer ${token}`
# If `disabled`, CSRF protection will be disabled.
# token: disabled

# If size is absent, it will try to fullscreen.
# size:
#   width: 1024
#   height: 768

# Of course, external server can also be used.
# cmd: 'java -jar shadowJar.jar'